package com.sample
 
import com.sample.Camara;


//TODO: FAZER AS 3 REGRAS CORRETAMENTE
/*
	Caso a temperatura de uma câmara de vacina chegue perto dos limites dos
	parâmetros, deve-se notificar os gestores;
	
	Caso a temperatura de uma câmara de vacina fique fora dos limites dos
	parâmetros definidos (situação grave), o gestor que estiver mais perto do local
	do armazenamento da vacina deve ser chamado para comparecer ao local;
	
	Caso a temperatura de uma câmara de vacina fique fora dos limites dos
	parâmetros definidos durante um certo intervalo de tempo (a ser definido), o
	sistema deve sugerir o descarte do produto. (VERIFICAR INTEGRIDADE DA VAC)
*/
 
/*
//PERGUNTAR PATRICIA

rule "Lote TempLimiar"
    when
    	$lote: Lote((vac.getTempMin() < cam.getTemperatura() && (vac.getTempMin()+2) > cam.getTemperatura()) || (vac.getTempMax() > cam.getTemperatura() && (vac.getTempMax()-2) < cam.getTemperatura()))
    	
    then
    	System.out.println("\nCAMARA: "+  $lote.getCam().getNome() +" - tempCam:" +  $lote.getCam().getTemperatura());
        $lote.getCam().notificarGestores();
end
*/

// SUGESTÃO: CRIAR TPO ENUMERADO PARA MENSAGENS PADRONIZADAS.

rule "Lote Temp Limiar Negativo"
    when
    	$lote: Lote(checarTempLimiar==1)
    then
    	System.out.println("\nTemp Limiar Negativo -> " + "CAMARA: "+  $lote.getCam().getNome() +" - tempCam:" +  $lote.getCam().getTemperatura());
        $lote.getCam().notificarGestores();
end

rule "Lote Temp Limiar Positivo"
    when
    	$lote: Lote(checarTempLimiar==2)
    then
    	System.out.println("\nTemp Limiar Positivo -> " + "CAMARA: "+  $lote.getCam().getNome() +" - tempCam:" +  $lote.getCam().getTemperatura());
        $lote.getCam().notificarGestores();
end


rule "Lote Temp Ruim Negativo"
    when
    	$lote: Lote(checarTempRuim==1)
    then
    	System.out.println("\nTemp Ruim Negativo -> " + "CAMARA: "+  $lote.getCam().getNome() +" - tempCam:" +  $lote.getCam().getTemperatura());
        $lote.getCam().chamarGestor();
end

rule "Lote Temp Ruim Positivo"
    when
    	$lote: Lote(checarTempRuim==2)
    then
    	System.out.println("\nTemp Ruim Positivo -> " + "CAMARA: "+  $lote.getCam().getNome() +" - tempCam:" +  $lote.getCam().getTemperatura());
        $lote.getCam().chamarGestor();
end


