package com.vac_controll.model;

import java.util.Date;
import java.util.ArrayList;

function long tempoAtual(){
return System.currentTimeMillis();
}

//TODO:
/*	
	- COMENTAR CÓDIGO
	- FAZER DIAGRAMA UML
	- PREPARAR SLIDES
*/



/*
Sugestões de roteiro para apresentações (com uso de slides) – 30 minutos cada grupo:

- Apresente visão geral do sistema desenvolvido (use figuras de preferencia), tipo:
- Visão geral das funcionalidades do sistema (o que o sistema é capaz de fazer?)
- Modelo de classes/componentes

- Como as funcionalidades citadas acima são implementadas (como o sistema é implementado em termos de regras drools, threads, sensores, etc.)
- Demonstração da ferramenta...
*/


// TEMPERATURA PERIGOSA - SEM REGISTRO
rule "Lote Temp Perigosa"
    when
    	$lote: Lote($codigoLote: checarTemp!=CodigoAlerta.TEMP_OK, $cam:camara, $util:util==true)
		Camara(this==$cam, $temp:temperatura)
		not (exists (TempRuim(lote == $lote, fim==null)))
    then
		insert(new TempRuim($lote, $temp, new Date(), $codigoLote));
		//System.out.println("Temp Perigosa");
end


rule "Lote Temp Diferente"
    when
    	$lote: Lote($codigoLote:checarTemp, $cam:camara, $util:util)
		Camara(this==$cam, $temp:temperatura)
		$tempRuim: TempRuim(lote == $lote, fim==null, codigo != $codigoLote)
    then
		$tempRuim.setFim(new Date());
		$tempRuim.setFoiAlterada(true);
		update($tempRuim);
		if($codigoLote != CodigoAlerta.TEMP_OK && $util==true){
			insert(new TempRuim($lote, $temp, new Date(), $codigoLote));
		}
		//System.out.println("Temp Diferente");
end


// DESCARTE DO LOTE DE VACINAS
rule "Descarte TempMin"
	when
		$lote: Lote($cam:camara, $vac:vacina, util==true)
		TempRuim(lote == $lote, $inicioTime: inicio.getTime(), fim==null, codigo==CodigoAlerta.TEMP_MIN)
		eval((tempoAtual()-$inicioTime) > Constante.LimiteExposicao)
		not (exists (Descarte(lote==$lote)))
	then
		insert(new Descarte(new Date(), $lote, CodigoAlerta.DESCARTE));
		//System.out.println("Descarte TempMin");
end


rule "Descarte TempMax"
	when
		$lote: Lote($cam:camara, $vac:vacina, util==true)
		TempRuim(lote == $lote, $inicioTime: inicio.getTime(), fim==null, codigo==CodigoAlerta.TEMP_MAX)
		eval((tempoAtual()-$inicioTime) > Constante.LimiteExposicao)
		not (exists (Descarte(lote==$lote)))
	then
		insert(new Descarte(new Date(), $lote, CodigoAlerta.DESCARTE));
		//System.out.println("Descarte TempMax");
end


// CONSULTAS (QUERIES)
query "novasTempRuim"
	tempRuim: TempRuim(foiAlterada)
end

query "novosDescartes"
	descarte: Descarte(id==null)
end

