package com.vac_controll.model;

import java.util.Date;
import java.util.ArrayList;

import com.vac_controll.controller.LoteController

function long currentTime(){
  return System.currentTimeMillis();
}

//TODO:
/*	
	- COMENTAR CÓDIGO
	- FAZER DIAGRAMA UML
	- PREPARAR SLIDES
*/



/*
Sugestões de roteiro para apresentações (com uso de slides) – 30 minutos cada grupo:

- Apresente visão geral do sistema desenvolvido (use figuras de preferencia), tipo:
- Visão geral das funcionalidades do sistema (o que o sistema é capaz de fazer?)
- Modelo de classes/componentes

- Como as funcionalidades citadas acima são implementadas (como o sistema é implementado em termos de regras drools, threads, sensores, etc.)
- Demonstração da ferramenta...
*/

declare TempRuimMax
	lote: Lote;
	temp: double;
	inicio: Date;
	fim: Date;
	valido: boolean;
end

declare TempRuimMin
	lote: Lote;
	temp: double;
	inicio: Date;
	fim: Date;
	valido: boolean;
end

declare descarte
	lote: Lote;
end



rule "Lote Temp Limiar Negativo"
    when
    	$lote: Lote(checarTempLimiar==CodigoAlerta.MARGEM_MIN, $util:util==true)
    then
end

rule "Lote Temp Limiar Positivo"
    when
    	$lote: Lote(checarTempLimiar==CodigoAlerta.MARGEM_MAX, util==true)
    then
end


rule "Lote Temp Ruim Negativo"
    when
    	$lote: Lote(checarTempRuim==CodigoAlerta.TEMP_MIN, $cam:camara, util==true)
    	Camara(this==$cam, $temp:temperatura)
    	not (exists (TempRuimMin(lote==$lote, valido==true)))
    then
    	insert (new TempRuimMin($lote, $temp, new Date(), null, true)); 
end


rule "Lote Temp Ruim Positivo"
    when
    	$lote: Lote(checarTempRuim==CodigoAlerta.TEMP_MAX, $cam:camara, util==true)
    	Camara(this==$cam, $temp:temperatura)
    	not (exists (TempRuimMax(lote==$lote, valido==true)))
    then
    	insert (new TempRuimMax($lote, $temp, new Date(), null, true));
end


rule "Lote Temp Dif Min"
    when
    	$lote: Lote(checarTempRuim != CodigoAlerta.TEMP_MIN, util==true)
    	$tempRuim: TempRuimMin(lote==$lote, valido==true)
    then
		$tempRuim.setFim(new Date());
		$tempRuim.setValido(false);
		update($tempRuim);
end


rule "Lote Temp Dif Max"
    when
    	$lote: Lote(checarTempRuim != CodigoAlerta.TEMP_MAX, util==true)
    	$tempRuim: TempRuimMax(lote==$lote, valido==true)
    then
		$tempRuim.setFim(new Date());
		$tempRuim.setValido(false);
		update($tempRuim);
end


rule "Descarte TempMin"
	when
		$lote: Lote($cam:camara, $vac:vacina, util==true)
		Camara(this==$cam, $temp:temperatura)
		TempRuimMin(lote == $lote, $inicioTime: inicio.getTime(), valido==true)
		eval((currentTime()-$inicioTime) > Constante.LimiteExposicao)
	then
		insertLogical(new descarte($lote));
		$lote.setUtil(false);
		update($lote);
end


rule "Descarte TempMax"
	when
		$lote: Lote($cam:camara, $vac:vacina, util==true)
		TempRuimMax(lote == $lote, $inicioTime: inicio.getTime(), valido==true)
		eval((currentTime()-$inicioTime) > Constante.LimiteExposicao)
		Camara(this==$cam, $temp:temperatura)
	then
		insertLogical(new descarte($lote));
		$lote.setUtil(false);
		update($lote);
end





