###
###     CRUD CAMARA
###

@URL_API = http://127.0.0.1:8080
@contentType = application/json


#   LIST
GET {{ URL_API }}/camara/
Content-Type: application/json

{}
###


#   RETRIEVE
GET {{ URL_API }}/camara/1
Content-Type: application/json

{}
###


#   CREATE
#   UFES: -20.273610030740326, -40.30586659439299
POST {{ URL_API }}/camara/
Content-Type: application/json

{
    "nome": "Camara 1 - UFES",
    "loc": {
        "latitude": -20.273610030740326,
        "longitude": -40.30586659439299
    },
    "temperatura": 16.0,
    "umidade": 80.0
}
###



#   UPDATE
#   ESTADIO_CARIACITY:  -20.332918400404424, -40.38515350717288
PUT {{ URL_API }}/camara/1
Content-Type: application/json

{   
    "temperatura": 12,
    "umidade": 80.0
}
###


#   DELETE
DELETE  {{ URL_API }}/camara/1
Content-Type: application/json

{}

###