###
###     CRUD VACINA
###

@URL_API = http://127.0.0.1:8080
@contentType = application/json


#   LIST
GET {{ URL_API }}/vacina/
Content-Type: application/json

{}
###


#   RETRIEVE
GET {{ URL_API }}/vacina/1
Content-Type: application/json

{}
###


#   CREATE
POST {{ URL_API }}/vacina/
Content-Type: application/json

{
    "nome": "Corona VAC",
    "tempMax": 20.0,
    "tempMin": 5.0,
    "margem": 20
}
###


#   UPDATE
PUT {{ URL_API }}/vacina/1/
Content-Type: application/json

{
    "nome": "sputnik V",
    "tempMax": 20.0,
    "tempMin": 0.0,
    "margem": 10
}
###


#   DELETE
DELETE  {{ URL_API }}/vacina/3/
Content-Type: application/json

{}
###