###
###     CRUD VACINA
###

@URL_API = http://127.0.0.1:8080
@contentType = application/json


#   LIST
GET {{ URL_API }}/vacina/
Content-Type: application/json

{}
###

#   RETRIVE
GET {{ URL_API }}/vacina/1
Content-Type: application/json

{}
###

#   CREATE
POST {{ URL_API }}/vacina/
Content-Type: application/json

{
    "nome": "corona vac",
    "tempMax": 15.0,
    "tempMin": 5.0,
    "margem": 10
}
###


#   UPDATE
PUT {{ URL_API }}/vacina/1/
Content-Type: application/json

{
    "nome": "sputnik V",
    "tempMax": 20.0,
    "tempMin": 0.0,
    "margem": 10
}
###


#   DELETE
DELETE  {{ URL_API }}/vacina/1/
Content-Type: application/json

{}
###


###
###     CRUD LOTE
###


#   LIST
GET {{ URL_API }}/lote/
Content-Type: application/json

{}
###

#   RETRIVE
GET {{ URL_API }}/lote/
Content-Type: application/json

{}
###

#   CREATE
POST {{ URL_API }}/lote/
Content-Type: application/json

{
    "qtd": 3,
    "vacina": {
        "id": 1
    },
    "validade": "2018-01-07",
    "util": true
}
###


#   UPDATE
PUT {{ URL_API }}/lote/2/
Content-Type: application/json

{
    "qtd": 3,
    "vacina": {
        "id": 2
    },
    "validade": "2018-01-07",
    "util": true
}
###


#   DELETE
DELETE  {{ URL_API }}/lote/1/
Content-Type: application/json

{}
###



###
###     CRUD CAMARA
###



#   LIST
GET {{ URL_API }}/camara/
Content-Type: application/json

{}

###

#   RETRIVE
GET {{ URL_API }}/camara/1
Content-Type: application/json

{}
###

#   CREATE
POST {{ URL_API }}/camara/
Content-Type: application/json

{
    "nome": "Camara de Cariacica",
    "loc": {
        "latitude": -20.33262247031378,
        "longitude": -40.377734714473526
    },
    "temperatura": 10.0,
    "umidade": 80.0
}
###


#   UPDATE
PUT {{ URL_API }}/camara/2
Content-Type: application/json

{
    "nome": "Camara de Vitoria",
    "loc": {
        "latitude": -20.33262247031378,
        "longitude": -40.377734714473526
    },
    "temperatura": 10.0,
    "umidade": 80.0
}
###

#   DELETE
DELETE  {{ URL_API }}/camara/2
Content-Type: application/json

{}

###



###
###     CRUD GESTOR
###



#   LIST
GET {{ URL_API }}/gestor/
Content-Type: application/json

{}

###

#   RETRIVE
GET {{ URL_API }}/gestor/1
Content-Type: application/json

{}
###

#   CREATE
POST {{ URL_API }}/gestor/
Content-Type: application/json

{
    "nome": "Usi",
    "email": "usi@ufes.br",
    "telefone": "(27) 99999-9999",
    "loc": {
        "latitude": -20.33262247031378,
        "longitude": -40.377734714473526
    },
    "cam": null
}
###


#   UPDATE
PUT {{ URL_API }}/gestor/2
Content-Type: application/json

{
    "nome": "Bel",
    "email": "bel@ufes.br",
    "telefone": "(27) 98888-8888",
    "loc": {
        "latitude": -20.33262247031378,
        "longitude": -40.377734714473526
    },
    "cam": null
}
###

#   DELETE
DELETE  {{ URL_API }}/gestor/2
Content-Type: application/json

{}

###





