###
###     CRUD LOTE
###

@URL_API = http://127.0.0.1:8080
@contentType = application/json


#   LIST
GET {{ URL_API }}/lote/
Content-Type: application/json

{}
###

#   LIST BY CAMARA
GET {{ URL_API }}/lote/camara/1
Content-Type: application/json

{}
###

#   CREATE
POST {{ URL_API }}/lote/
Content-Type: application/json

{
    "qtd": 100,
    "vacina": {
        "id": 1
    },
    "camara": {
        "id": 1
    },
    "validade": "2021-05-20"
}
###

